import Anthropic from '@anthropic-ai/sdk';

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

export async function callLLM(systemPrompt, history, userMessage) {
  const response = await client.messages.create({
    model: 'claude-3-5-sonnet-20241022',
    max_tokens: 4096,
    system: systemPrompt,
    messages: [
      ...history,
      { role: 'user', content: userMessage }
    ],
  });

  const textOutput = response.content[0].text.trim();
  
  // Clean up any potential markdown code block wrappers if generated by the LLM
  const cleanJsonString = textOutput.replace(/^```json\s*|```$/g, '');
  return JSON.parse(cleanJsonString);
}
